---
version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql.puppet.vm
    volumes:
      - mysql-persistent-volume:/tmp
    command: mysqld --datadir=/tmp/mysqldata --slow_query_log=1 --log_output=TABLE --log-queries-not-using-indexes --event-scheduler=ON
    environment: &mysql-default-environment
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: fleet
      MYSQL_USER: fleet
      MYSQL_PASSWORD: insecure
    ports:
      - "3306:3306"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog.puppet.vm
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:3.2.4
    container_name: redis.puppet.vm
    ports:
      - "6379:6379"
  
  fleetdm:
    image: 'fleetdm/fleet:latest'
    container_name: fleet.puppet.vm
    command: fleet serve
    environment:
      FLEET_MYSQL_ADDRESS: 'mysql.puppet.vm:3306'
      FLEET_SERVER_ADDRESS: 'fleet.puppet.vm:443'
      FLEET_MYSQL_DATABASE: fleet
      FLEET_MYSQL_PASSWORD: toor
      FLEET_MYSQL_USERNAME: fleet
      FLEET_AUTH_JWT_KEY: FleetFleetFleet
      FLEET_SERVER_CERT: '/etc/fleet/fleet.crt'
      FLEET_SERVER_KEY: '/etc/fleet/fleet.key'
      FLEET_SERVER_TLS: true
      
volumes:
  mysql-persistent-volume:
